### ISSUE TITLE
Problems generating barcodes with the checksum already in the text

### ISSUE THREAD

**Issue by christeredvartsen** [zendframework/zend-barcode#13]
I have a database with a bunch of EAN13 codes that already includes the checksums (the last character in the code). I'm trying to render barcodes out of these but I'm only getting the following error message:

"The input should have a length of 13 characters"

Reproducible code:

``` php
$barcodeOptions = [
    'text' => '7090037170787' // valid barcode including the checksum character
];
$rendererOptions = [
    'imageType' => 'png',
];
$barcode = \Zend\Barcode\Barcode::factory(
    'ean13',
    'image',
    $barcodeOptions,
    $rendererOptions
);
$barcode->render();
```

This results in an image that has the error message mentioned above.

Is there any other options I can use that informs the barcode object and/or renderer that the checksum is already included in the `text` option? I could of course do `'text' => substr('7090037170787', 0, -1)` but this seems rather counterintuitive.

**Comment by Gemorroj** [comment]
Same problem.
And have this problem for ITF-14...

**Comment by froschdesign** [comment]
@christeredvartsen 
Look at the [docs (`withChecksumInText`)](https://zendframework.github.io/zend-barcode/objects/#common-options) or at the [code](https://github.com/zendframework/zend-barcode/blob/master/src/Object/AbstractObject.php#L709).

**Comment by povils** [comment]
@froschdesign is still wrong [code](https://github.com/zendframework/zend-barcode/blob/master/src/Object/AbstractObject.php#L1278) . Because for example EAN13 you will get $value with 14 length

**Comment by silverslice** [comment]
Ean13 class [sets](https://github.com/zendframework/zend-barcode/blob/master/src/Object/Ean13.php#L57) mandatoryChecksum to true, so setting `withChecksumInText` has not effect. It's confusing, but you should pass 12 characters instead of 13.
