### ISSUE TITLE
Orientation breaks barcode

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-barcode#27]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://github.com/zendframework/zendframework/issues/7130
User: @yahor-kalinin
Created On: 2015-01-16T21:48:16Z
Updated At: 2015-10-02T09:22:03Z
Body
When I'm trying to render a vertical Code39 barcode it's looks like:
![screenshot from 2015-01-16 04 03 26](https://cloud.githubusercontent.com/assets/302643/5769999/a88607b2-9d34-11e4-9ed6-7ce51de182e7.png)

Code example:

``` php
$barcode = new Code39([
    'orientation' => 90,
    'text'        => 'ZEND',
    'drawText'    => false
]);

$renderer = new Image([
    'barcode' => $barcode,
]);

$renderer->render();
```

When I change this line:
https://github.com/zendframework/zend-barcode/blob/625b5a7f4cf50d19f87eedefd591365a7d6b52fb/src/Object/AbstractObject.php#L1162
to:

``` php
$point1 = $this->rotate($xpos - 1, $ypos + $bar[2] * $barLength);
```

The barcode renders in right way:
![screenshot from 2015-01-16 04 04 44](https://cloud.githubusercontent.com/assets/302643/5770007/d407f1fc-9d34-11e4-85f8-bf8036ac42c8.png)

But, this change breaks render of horizontal barcodes.
Can someone help me in determining the source of this behavior?

---
### Comment

User: @ArtemGordinsky
Created On: 2015-10-02T09:21:41Z
Updated At: 2015-10-02T09:22:03Z
Body
Encountered the exact same bug in ZF 1. Does anyone have any workarounds besides manually rotating the generated image?

---

**Comment by russell-pa** [comment]
I ran into this yesterday myself. I found a solution that works in any 0/90/160/270 orientation (maybe others) by overriding the drawPolygon of SVG and making use of the same logic used for `rotate` in Barcode's AbstractObject.

In case anyone else runs into this issue, or someone wants to incorporate this into the repository:

```php
use Zend\Barcode\Renderer\Svg;

/**
 * @inheritDoc
 */
class SvgRotated extends Svg
{
    /**
     * @inheritDoc
     */
    protected function drawPolygon($points, $color, $filled = true)
    {
        /*
         * The points expect a 1px collapsed stroke that doesn't exist in SVG.
         * The underlying drawPolygon method uses cos/sin on orientation, which causes floating point offsets.
         * Instead by applying the rotate method on the default 1,0 stroke padding, we get a rotated 1px stroke.
         */
        $rotate = $this->rotate(1, 0, $this->getBarcode()->getOrientation());

        $color = 'rgb(' . implode(',', [($color & 0xFF0000) >> 16,
                ($color & 0x00FF00) >> 8,
                ($color & 0x0000FF)]) . ')';
        $newPoints = [
            $points[0][0] + $this->leftOffset,
            $points[0][1] + $this->topOffset,
            $points[1][0] + $this->leftOffset,
            $points[1][1] + $this->topOffset,
            $points[2][0] + $this->leftOffset + $rotate[0],
            $points[2][1] + $this->topOffset + $rotate[1],
            $points[3][0] + $this->leftOffset + $rotate[0],
            $points[3][1] + $this->topOffset + $rotate[1],
        ];
        $newPoints = implode(' ', $newPoints);
        $attributes = [];
        $attributes['points'] = $newPoints;
        $attributes['fill'] = $color;

        // SVG passes a rect in as the first call to drawPolygon, we'll need to intercept
        // this and set transparency if necessary.
        if (! $this->drawPolygonExecuted) {
            if ($this->transparentBackground) {
                $attributes['fill-opacity'] = '0';
            }
            $this->drawPolygonExecuted = true;
        }

        $this->appendRootElement('polygon', $attributes);
    }

    /**
     * Apply rotation on a point in X/Y dimensions
     *
     * @param  float $x1 x-position before rotation
     * @param  float $y1 y-position before rotation
     * @param    int $orientation degrees of rotation
     * @return array Array of two elements corresponding to the new XY point
     * @see \Zend\Barcode\Object\AbstractObject::rotate()
     */
    private function rotate($x1, $y1, $orientation)
    {
        $x2 = $x1 * cos($orientation / 180 * pi())
            - $y1 * sin($orientation / 180 * pi());
        $y2 = $y1 * cos($orientation / 180 * pi())
            + $x1 * sin($orientation / 180 * pi());
        return [intval($x2), intval($y2)];
    }
}
```
