### ISSUE TITLE
Appears to be tightly coupled to Zend Validate?

### ISSUE THREAD

**Issue by delboy1978uk** [zendframework/zend-barcode#34]
I'm trying to create my own Barcode class for generating GS1-128 barcodes. But there doesn't appear to be a way to set the validator. Or is there?

Fatal error: Uncaught exception 'Zend\Validator\Exception\InvalidArgumentException' with message 'Barcode adapter matching "Zend\Validator\Barcode\Gs1" not found"

```php
<?php

require_once 'vendor/autoload.php';

use Zend\Barcode\Barcode;

// Only the text to draw is required.
$barcodeOptions = array(
    'text' => '1234567890etc',
    'barcodeNamespace' => 'My\Package\Barcode',
);

// No required options.
$rendererOptions = array();

$traversable = new ArrayObject();
$traversable['barcode'] = 'My\Package\Barcode\Gs1';
$traversable['params'] = $barcodeOptions;

$renderer = Barcode::factory(
    $traversable,
    'image',
    $barcodeOptions,
    $rendererOptions
)->render();
```

**Comment by froschdesign** [comment]
> But there doesn't appear to be a way to set the validator. Or is there?

Please look at the [`Zend\Barcode\Object\AbstractObject::validateSpecificText()`](https://github.com/zendframework/zend-barcode/blob/master/src/Object/AbstractObject.php#L1262) method or compare with [`Zend\Barcode\Object\Upce`](https://github.com/zendframework/zend-barcode/blob/master/src/Object/Upce.php).

**Comment by delboy1978uk** [comment]
Hi Frank, thank you for your Feedback, I'll look into it!

**Comment by delboy1978uk** [comment]
Got it using this code, thanks again!
```php
<?php

require_once 'vendor/autoload.php';

use Zend\Barcode\Barcode;

// Only the text to draw is required.
$barcodeOptions = new ArrayIterator(array(
    'rendererParams' => array (),
    'renderer' => 'image',
    'barcodeParams' => array (
        'text' => '(255)9980101762001(3902)19099(17)160610(21)358139065068904056',
        'withChecksum'=> true,
        'barcodeNamespace'=> 'My\Package\Barcode',
    ),
    'barcode' => 'My\Package\Barcode\Gs1',
));


$renderer = Barcode::factory($barcodeOptions)->render();
```

**Comment by thomasvargiu** [comment]
@delboy1978uk Can you share your implementation?
