### ISSUE TITLE
Add PHP 7.2 support, drop HHVM

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zend-barcode#37]
* Update Travis configuration
* Check Travis results

**Comment by froschdesign** [comment]
Related to #36 and #25

**Comment by ThomasTr** [comment]
@weierophinney could you please merge this pull request as it supports PHP 7.2

**Comment by michalbundyra** [comment]
@froschdesign It can be closed now, as [2.7.0](https://github.com/zendframework/zend-barcode/releases/tag/release-2.7.0) has been released.
